name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2

      - name: Install elm, elm-format and cache the ELM_HOME directory
        uses: mpizenberg/elm-tooling-action@v1.2
        with:
          cache-key: elm-home-${{ hashFiles('elm-tooling.json', 'elm.json') }}

      - name: Making sure the installation worked
        run: npx elm --version

      - name: elm make
        run: |
            npx elm make --output /dev/null && cd examples && npx elm make src/*.elm --output /dev/null && cd ..

      - name: elm test examples
        run: |
            npx elm-test-rs && cd examples && npx elm-test-rs elm-test && cd ..

      - name: elm-analyse
        run: |
            npm install -g elm-analyse

      - name: elm-analyse
        run: |
            elm-analyse && cd examples && elm-analyse && cd ..

